// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load both .env and .env.local so the CLI sees the same values Next.js does
// at runtime. .env.local wins.
loadEnv({ path: ".env" });
loadEnv({ path: ".env.local", override: true });

// Prefer DIRECT_URL for CLI/migrations (bypasses the pooler). Runtime uses
// DATABASE_URL through the driver adapter in src/lib/prisma.ts.
const url = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
